### ISSUE TITLE
Missing SHACL validation result in validate API output

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/register#100] opened 2021-03-29 12:16 UTC
Validating https://data.spinque.com/ld/data/oorlogsbronnen/oorlog_in_blik/ results in:
```
Status: 400

{"quads":{}}
```

**Comment by ddeboer** [comment] 2021-03-29 12:56
Duplicate of #90.

**Closed by ddeboer** 2021-03-29 12:56 UTC

**Comment by coret** [comment] 2021-03-29 15:46
https://github.com/netwerk-digitaal-erfgoed/register/pull/79 was not propagated to demo
now fixed via https://github.com/netwerk-digitaal-erfgoed/registry-demo/commit/1323dac91d2625128f1098beecebf410760a48d8
